version: '3.5'

services:
  postgres:
    # memenuhi kriteria nomor 1.a
    container_name: postgres_container_zuhadharkasyalhikam
    # memenuhi kriteria nomor 1.b
    image: postgres:latest
    # memenuhi kriteria nomor 1.c
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # mengambil value ke file user-and-password.env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # sama dengan variable POSTGRES_USER
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    # memenuhi kriteria nomor 1.d (binding port 21 + 3 digit akhir nim(148))
    ports:
      - "21:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    # memenuhi kriteria nomor 2.a
    container_name: pgadmin_container_zuhadharkasyalhikam
    # memenuhi kriteria nomor 2.b
    image: dpage/pgadmin4:latest
    #
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    # memenuhi kriteria nomor 2.c (binding port 21 + 3 digit akhir nim(148))
    ports:
      - "22148:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: